apiVersion: v1
kind: BuildConfig
metadata:
  name: grpcdev-builder
  annotations:
    openshift.io/build-config.name: grpcdev-builder
  labels:
    build: grpcdev-builder
    buildconfig: grpcdev-builder
    openshift.io/build-config.name: grpcdev-builder
    openshift.io/build.start-policy: Serial
spec:
  nodeSelector: null
  output:
    pushSecret:
      name: dockhub-hughestech3
    to:
      kind: DockerImage
      name: hughestech/grpc-i386-cmake
  source:
    contextDir: cmake
    git:
      ref: master
      uri: 'https://github.com/hughestech/grpcdev'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: hughestech/grpc-i386-builder
    type: Docker
  triggeredBy:
    - message: Manually triggered
