apiVersion: v1
kind: BuildConfig
metadata:
  name: grpcdev-wine
  annotations:
    openshift.io/build-config.name: grpcdev-wine
  labels:
    build: grpcdev-wine
    buildconfig: grpcdev-wine
    openshift.io/build-config.name: grpcdev-wine
    openshift.io/build.start-policy: Serial
spec:
  nodeSelector: null
  output:
    pushSecret:
      name: dockhub-hughestech3
    to:
      kind: DockerImage
      name: hughestech/grpc-i386-fule:wine-2.0.2
  source:
    contextDir: wine
    git:
      ref: master
      uri: 'https://github.com/hughestech/grpcdev'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: hughestech/grpc-i386-full:cmake
    type: Docker
  triggeredBy:
    - message: Manually triggered
